PYTHON = python3
MAIN_PROGRAM = main.py
VIRTUAL_MACHINE = vm.py
LOADER = loader.py
FACTORIAL_LIB = factorial_library.py
FIBONACCI_LIB = fibonacci_library.py

run:
	$(PYTHON) $(MAIN_PROGRAM)

clean:
	rm -f *.pyc
	rm -rf __pycache__  # cache
