#!/usr/bin/env python3
# Generated by PL/0 Compiler

# Block start
    n = 0  # Variable declaration
    fact = 0  # Variable declaration
    i = 0  # Variable declaration
    def factorial():
        # Block start
            fact = 1
            i = 1
            while (i <= n):
                fact = (fact * i)
                i = (i + 1)
    
    n = int(input('Enter value for n: '))
    factorial()
    print(fact)