        ORG     0100h       ; Start at 0x100

COUNT   EQU     8000h       ; Counter variable

START:  LD      A, 0        ; Init counter
        LD      (COUNT), A
LOOP:   LD      A, (COUNT)  ; Get counter
        CP      10          ; Done? (0-9)
        JP      Z, DONE
        ADD     A, 30h      ; To ASCII '0'-'9'
        OUT     (2), A      ; Print
        LD      A, (COUNT)
        INC     A           ; Increment
        LD      (COUNT), A
        JP      LOOP        ; Repeat

DONE:   LD      A, 0Ah      ; Line feed
        OUT     (2), A
        JP      0000h       ; Halt

        END
